apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: dotnet5angular
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dotnet5angular
  project: "demo"
  syncPolicy:   
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  source:
    path: dev
    repoURL: https://github.com/blcporgs/dotnet5angular-deployments.git