apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: dotnet5angular
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: ""
  source:
    path: dev
    repoURL: https://github.com/blcporgs/dotnet5angular-deployments.git
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""